### ISSUE TITLE
Whether to consider the use of protein 3D structure to predict affinity

### ISSUE THREAD

**Issue by zhouhao-learning** [hkmztrk/DeepDTA#13]
Hello, I recently saw some predictions about the use of protein 3D structures to predict affinity. Using 3D convolutional neural networks, are you interested? Or have you been exposed to some feature extraction methods for protein 3D structures, can you share them with me? ?

**Comment by hkmztrk** [comment]
Hello @zhouhao-learning, it is of course possible to integrate 3D information if it is available. DeepDTA is a sequence based model, therefore we didn't use 3D coordinates or related features. 

However, you can always integrate more information (rather than using only sequences) in your model including 3D-related features (again if available). I can refer to the [PDB-bind ](http://www.pdbbind-cn.org/) database for such data.

**Comment by zhouhao-learning** [comment]
@hkmztrk 
If you are interested, can you refer to it together? I think this is the most novel idea. Can you tell me the email easily? Convenient communication

**Comment by hkmztrk** [comment]
you can e-mail me at  [here ](hakime.ozturk@boun.edu.tr)
