### ISSUE TITLE
Prediction of binding affinity using DeepDTA interpretation

### ISSUE THREAD

**Issue by lmlmmma** [hkmztrk/DeepDTA#25]
First of all, thank you for developing this framework. I tested the deepdta-toy and I was not super sure how to find the affinity values of interest. I used the exact same files as the ones in the deepdta-toy folder and added the Y to mytest folder. I think I got 4 txt files (predicted labels 0-3) with 4 numbers in each file. Are these files describing the affinity? If so, which file should I use to look for the predicted affinity between each compound and the proteins?

Thanks for your help in advance!

**Comment by hkmztrk** [comment]
Hello @lmlmmma, sorry for the late reply. Four text files are in correspondence to parameter search: 
```
                          --seq_window_lengths 8 12 \
                          --smi_window_lengths 4 8 \
```
In theory, all these four text files have predicted affinity scores.  However, since we don't have the experimental values (or ground truth) for novel drug-target pairs,  I also cannot suggest a parameter combination will provide the best result.  At this point, it is a bit trial-test. If you have at least some portion of your test data with known values, you can try and see which combination works best, and then directly use those values to predict novel interactions.

Hope this helps.

**Comment by lmlmmma** [comment]
@hkmztrk Thank you very much for your reply. I also see 4 values in each txt file when I used 1 chemical and 2 proteins. I am just wondering if you have any recommendation as to how to find which values corresponds to which combination of chemical and protein fasta? I plan to use my own data with 100 chemicals and 100 proteins in the end to see which combination will provide the best predicted affinity and there will not be any known affinities. Thank you again for your help!

**Comment by hkmztrk** [comment]
@lmlmmma could you copy the content of the txt file here?
