### ISSUE TITLE
Question about KIBA score

### ISSUE THREAD

**Issue by baehaeli** [hkmztrk/DeepDTA#29]
Hello, I am very interested in your work.

In the KIBA dataset, you use the KIBA score as suggested in 
'Making Sense of Large-Scale Kinase Inhibitor Bioactivity Data Sets: A Comparative and Integrative Analysis'. (Tang et al, 2014)

It seems the KIBA score suggested in Tang's research and DeepDTA is different.

For example, the KIBA score between 'CHEMBL98350' and 'P48736' is reported as 3.21982 in Tang et al. However, the KIBA score of DeepDTA is not.

So I would like to know how you make the KIBA score detail, such as the parameter of Li and Ld when calculating the KIBA score.

<img width="164" alt="eq1" src="https://user-images.githubusercontent.com/11719464/149651827-2519850e-1770-425c-b9da-f6e970f85266.PNG">
<img width="305" alt="eq2" src="https://user-images.githubusercontent.com/11719464/149651837-e7e9fb0e-b3ee-47e1-890a-acb08aa6e107.PNG">

Thank you

**Comment by hkmztrk** [comment]
Hi @baehaeli thanks for your interest!

We didn't do any changes on the original KIBA scores, but used the KIBA dataset provided in SimBoost (He et al., 2017) study https://jcheminf.biomedcentral.com/articles/10.1186/s13321-017-0209-z

**Comment by baehaeli** [comment]
Thank you for the reply.

I wonder if you have checked the reason for the different KIBA scores.

**Comment by hkmztrk** [comment]
Hi @baehaeli, thanks for reminding me, I totally forgot to respond. Again please see SimBoost (He et al., 2017) paper for details, they perform a transformation on KIBA as follows: 

`In an additional preprocessing step, we transformed the KIBA dataset by taking the negative of each value and adding the minimum to all values in order to obtain a threshold where all values above the threshold are classified as binding. The KIBA threshold of 3.0 in the untransformed dataset then becomes 12.1. `

In DeepDTA we directly use these outputs from He et al, without further transformation. Hope this helps.

**Comment by baehaeli** [comment]
Thank you!
