### ISSUE TITLE
How to embed proteins using ligands' smiles?

### ISSUE THREAD

**Issue by xuzhang5788** [hkmztrk/DeepDTA#3]
Thank you for your post. I read your paper, but I am not very clear about how to represent proteins using ligands' smiles. Would you like to explain it again? Many thanks

**Comment by hkmztrk** [comment]
Hello @xuzhang5788 , thanks a lot for your interest in our paper. 
I should clarify that in DeepDTA, proteins are represented with their sequences. However, in another model, we use the SMILES string of the interacting ligands of the protein, [here](https://github.com/hkmztrk/SMILESVecProteinRepresentation). The repo has more detail explanation in README. If you have specific questions regarding to that study, please let me know.

**Comment by hkmztrk** [comment]
Hello @xuzhang5788, here we used amino acid sequences. I agree with you about the lost structure information, however not for all proteins the structure is determined although sequence is always available.

Using interacting ligands' SMILES, we aimed to capture function information of protein, because we know that similar proteins tend to bind similar ligands.
