### ISSUE TITLE
Help with installation

### ISSUE THREAD

**Issue by lindachiap** [hkmztrk/DeepDTA#37]
Hi,
I am new to python and would like to install and use DeepDTA, but the README file does not give any details about installation. Please could you let me know how best to install and start running DeepDTA? Is there a way I can install it with pip? Do I have to clone the repo? If so, how do I start using the package from there?
Any help much appreciated.

**Comment by hkmztrk** [comment]
Hi @lindachiap, you first need to clone the repository and then create an environment with the specified versions of the required packages in https://github.com/hkmztrk/DeepDTA#requirements.  

Once you activated the environment you should be able to replicate the experiments using the instructions here https://github.com/hkmztrk/DeepDTA#usage 

The implementation in this repo uses Keras - if you are interested in working with Pytorch, please check this thread: https://github.com/hkmztrk/DeepDTA/issues/35

**Comment by hkmztrk** [comment]
Thanks @marvinvanaalst! I also added a tested environment just now. 

@lindachiap hope you were able to solve this. 

Otherwise, please refer to [deepdta.yml](https://github.com/hkmztrk/DeepDTA/blob/master/deepdta.yml) or @marvinvanaalst 's suggested environment [here](https://github.com/hkmztrk/DeepDTA/pull/38/commits/24e48cc4154aefdd97a34551c0229eebf810d3e0).
