### ISSUE TITLE
Regarding data leakage caused by amino acid sequences in the data set

### ISSUE THREAD

**Issue by jinhang23** [hkmztrk/DeepDTA#43]
In the data/davis/Proteins.txt file, different mutations of the EGFR gene (such as G719C, G719S, L747E749del) appear to have the same amino acid sequence. This raised a concern for me: why were these genetic mutations not reflected in the amino acid sequence? Furthermore, these samples all have the same affinity in the dataset. Randomly divide 20% as the test data set. About 25% of the data in the test data has appeared in the training data. I am worried that there is a potential risk of data leakage in the model based on these sequences.
![1706088241770](https://github.com/hkmztrk/DeepDTA/assets/90559792/6143f982-61d0-42fa-bc12-0abffea48a52)

**Comment by htalibart** [comment]
Hello, I see that this issue was marked as "completed" but I see no reply, what was the response?
Thank you

**Comment by kkkayle** [comment]
Thank you for your attention. As the person who raised the question, I've noticed that many proteins have mutations, yet their corresponding sequences have not changed. Due to my lack of professional background knowledge, I found that a large number of literature references are using the sequence information from these datasets. Therefore, I suspect that I might have misunderstood something. Unfortunately, I do not yet know the answer to this question.


Z.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hkmztrk/DeepDTA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月20日(星期三) 下午5:06
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [hkmztrk/DeepDTA] Regarding data leakage caused by amino acid sequences in the data set (Issue #43)





 
Hello, I see that this issue was marked as "completed" but I see no reply, what was the response?
 Thank you
